In [2]:
import random
import numpy as np
import torch

In [3]:
# Bài 1: Tạo Tensor cơ bản

a = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]],
    dtype=torch.int32
)

print("Tensor a:")
print(a)

print("\nKích thước:", a.shape)
print("Số chiều:", a.ndim)
print("Kiểu dữ liệu:", a.dtype)

Tensor a:
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

Kích thước: torch.Size([2, 3])
Số chiều: 2
Kiểu dữ liệu: torch.int32


In [4]:
# Bài 2: Tạo các Tensor thường dùng

a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

# Tensor 5 x 5 toàn giá trị 10
f = torch.full((5, 5), 10)

print("Tensor rand:")
print(a)

print("\nTensor randn:")
print(b)

print("\nTensor zeros:")
print(c)

print("\nTensor ones:")
print(d)

print("\nMa trận đơn vị:")
print(e)

print("\nTensor 5 x 5 toàn số 10:")
print(f)

Tensor rand:
tensor([[0.3082, 0.6008, 0.6546, 0.6597],
        [0.1063, 0.4599, 0.1482, 0.7375],
        [0.8831, 0.5710, 0.9197, 0.0146]])

Tensor randn:
tensor([[-1.2374, -1.4971,  3.1491,  2.7289],
        [-0.9516,  1.4630, -1.6719, -1.0576],
        [ 0.8746, -1.1362, -0.5578,  1.1063]])

Tensor zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Ma trận đơn vị:
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Tensor 5 x 5 toàn số 10:
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


In [5]:
# Bài 3: Kiểm tra thông tin Tensor

a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)

print("\nShape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

print("\nGiải thích torch.Size([2, 3, 4]):")
print("Tensor có 3 chiều với kích thước 2 x 3 x 4.")
print("Tổng số phần tử:", a.numel())

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32

Giải thích torch.Size([2, 3, 4]):
Tensor có 3 chiều với kích thước 2 x 3 x 4.
Tổng số phần tử: 24


In [6]:
# Bài 4: Slicing và Indexing

a = torch.randn(3, 4, 5)

print("Original tensor:")
print(a)

print("\nTensor a[1]:")
print(a[1])

print("\nShape của a[1]:")
print(a[1].shape)

print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

print("\nShape của a[1:, 2:4]:")
print(a[1:, 2:4].shape)

# Lấy hai phần tử cuối cùng trên chiều thứ ba
print("\nHai phần tử cuối cùng trên chiều thứ ba:")
print(a[:, :, -2:])

print("\nShape:")
print(a[:, :, -2:].shape)

Original tensor:
tensor([[[ 2.4898,  1.2053, -0.7160, -0.3706,  0.1326],
         [-0.2633, -0.3204,  0.7914, -1.2042,  0.9398],
         [ 0.6257, -0.2486,  0.5196,  0.4577,  0.0285],
         [ 1.7165,  0.2419,  2.3818, -1.4635,  0.8178]],

        [[-1.6263, -0.1056, -1.3114, -0.6917, -0.2519],
         [ 0.2585, -0.1592, -1.5339, -1.1104,  1.2487],
         [-1.0358,  0.0871, -0.4901,  0.4928, -0.8560],
         [ 0.6956,  0.4074,  1.5438,  0.7379, -1.6826]],

        [[-2.2944, -1.4498, -1.0557, -0.4050,  1.2811],
         [-0.8082, -0.6893,  0.5537, -0.2603, -1.0398],
         [-1.0069,  0.3897,  0.2634, -1.4353, -0.1964],
         [-1.2379, -0.9497,  0.6355,  1.0364,  0.7638]]])

Tensor a[1]:
tensor([[-1.6263, -0.1056, -1.3114, -0.6917, -0.2519],
        [ 0.2585, -0.1592, -1.5339, -1.1104,  1.2487],
        [-1.0358,  0.0871, -0.4901,  0.4928, -0.8560],
        [ 0.6956,  0.4074,  1.5438,  0.7379, -1.6826]])

Shape của a[1]:
torch.Size([4, 5])

Tensor a[1:, 2:4]:
tensor([[[-1.0

In [7]:
# Bài 5: Reshape và Flatten

a = torch.randn(3, 4)

print("Original:")
print(a)

print("\nShape ban đầu:")
print(a.shape)

print("\nFlatten:")
flatten = a.ravel()
print(flatten)

print("\nShape sau Flatten:")
print(flatten.shape)

print("\nSố phần tử trước reshape:")
print(a.numel())

# Reshape thành 3 x 2 x 2
b = a.reshape(3, 2, 2)

print("\nReshape thành 3 x 2 x 2:")
print(b)

print("\nShape:")
print(b.shape)

print("\nSố phần tử sau reshape:")
print(b.numel())

# Reshape thành 2 x 6
c = a.reshape(2, 6)

print("\nReshape thành 2 x 6:")
print(c)

print("\nShape:")
print(c.shape)

Original:
tensor([[ 2.0223, -0.9663, -1.4395, -0.3282],
        [ 0.2018, -2.6462,  0.0542,  0.2508],
        [ 1.5041, -0.6961,  1.0362, -0.0073]])

Shape ban đầu:
torch.Size([3, 4])

Flatten:
tensor([ 2.0223, -0.9663, -1.4395, -0.3282,  0.2018, -2.6462,  0.0542,  0.2508,
         1.5041, -0.6961,  1.0362, -0.0073])

Shape sau Flatten:
torch.Size([12])

Số phần tử trước reshape:
12

Reshape thành 3 x 2 x 2:
tensor([[[ 2.0223, -0.9663],
         [-1.4395, -0.3282]],

        [[ 0.2018, -2.6462],
         [ 0.0542,  0.2508]],

        [[ 1.5041, -0.6961],
         [ 1.0362, -0.0073]]])

Shape:
torch.Size([3, 2, 2])

Số phần tử sau reshape:
12

Reshape thành 2 x 6:
tensor([[ 2.0223, -0.9663, -1.4395, -0.3282,  0.2018, -2.6462],
        [ 0.0542,  0.2508,  1.5041, -0.6961,  1.0362, -0.0073]])

Shape:
torch.Size([2, 6])


In [8]:
# Bài 6: Phép toán và nhân ma trận

a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a:")
print(a)

print("\nb:")
print(b)

print("\na + b:")
print(a + b)

print("\na / b:")
print(a / b)

print("\na^2:")
print(a ** 2)

print("\na * b:")
print(a * b)

print("\na @ b.T:")
print(a @ b.T)

print("\nShape của a * b:")
print((a * b).shape)

print("\nShape của a @ b.T:")
print((a @ b.T).shape)

print("\nNhận xét:")
print("a * b là phép nhân từng phần tử tương ứng.")
print("a @ b.T là phép nhân ma trận.")

a:
tensor([[ 0.5735,  0.7793, -0.2501],
        [ 0.0460,  0.2726, -1.7927]])

b:
tensor([[ 0.0376, -0.1683,  0.8193],
        [-0.0888,  0.7472, -0.3629]])

a + b:
tensor([[ 0.6112,  0.6110,  0.5693],
        [-0.0428,  1.0197, -2.1555]])

a / b:
tensor([[15.2339, -4.6300, -0.3052],
        [-0.5179,  0.3648,  4.9404]])

a^2:
tensor([[3.2894e-01, 6.0732e-01, 6.2530e-02],
        [2.1133e-03, 7.4300e-02, 3.2136e+00]])

a * b:
tensor([[ 0.0216, -0.1312, -0.2049],
        [-0.0041,  0.2037,  0.6505]])

a @ b.T:
tensor([[-0.3145,  0.6221],
        [-1.5129,  0.8501]])

Shape của a * b:
torch.Size([2, 3])

Shape của a @ b.T:
torch.Size([2, 2])

Nhận xét:
a * b là phép nhân từng phần tử tương ứng.
a @ b.T là phép nhân ma trận.


In [9]:
# Bài 7: Các hàm thống kê trên Tensor

a = torch.randn(3, 4)

print("Tensor a:")
print(a)

print("\nMean theo cột - dim=0:")
print(torch.mean(a, dim=0))

print("\nStandard deviation theo cột - dim=0:")
print(torch.std(a, dim=0))

print("\nCumulative sum theo cột - dim=0:")
print(torch.cumsum(a, dim=0))

print("\nMean theo hàng - dim=1:")
print(torch.mean(a, dim=1))

print("\nStandard deviation theo hàng - dim=1:")
print(torch.std(a, dim=1))

print("\nCumulative sum theo hàng - dim=1:")
print(torch.cumsum(a, dim=1))

print("\nNhận xét:")
print("dim=0: tính toán theo chiều dọc, kết quả theo từng cột.")
print("dim=1: tính toán theo chiều ngang, kết quả theo từng hàng.")

Tensor a:
tensor([[ 0.0521,  0.4358,  0.0891,  1.5460],
        [ 1.3647, -0.1996,  0.1151, -0.9840],
        [ 1.8305,  0.8094,  1.0939, -0.8232]])

Mean theo cột - dim=0:
tensor([ 1.0824,  0.3485,  0.4327, -0.0871])

Standard deviation theo cột - dim=0:
tensor([0.9222, 0.5101, 0.5727, 1.4166])

Cumulative sum theo cột - dim=0:
tensor([[ 0.0521,  0.4358,  0.0891,  1.5460],
        [ 1.4168,  0.2361,  0.2042,  0.5620],
        [ 3.2473,  1.0455,  1.2981, -0.2613]])

Mean theo hàng - dim=1:
tensor([0.5307, 0.0740, 0.7276])

Standard deviation theo hàng - dim=1:
tensor([0.6985, 0.9767, 1.1199])

Cumulative sum theo hàng - dim=1:
tensor([[0.0521, 0.4878, 0.5770, 2.1230],
        [1.3647, 1.1651, 1.2802, 0.2961],
        [1.8305, 2.6399, 3.7338, 2.9106]])

Nhận xét:
dim=0: tính toán theo chiều dọc, kết quả theo từng cột.
dim=1: tính toán theo chiều ngang, kết quả theo từng hàng.


In [10]:
# Bài 8: Autograd cơ bản

# Hàm y = x^2
x = torch.tensor(3.6, requires_grad=True)

y = x * x

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

print("\nTính thủ công:")
print("y = x^2")
print("dy/dx = 2x")
print("Tại x = 3.6:")
print("dy/dx =", 2 * 3.6)


# Hàm y = 3*x^2 + 2*x + 1
x = torch.tensor(3.6, requires_grad=True)

y = 3 * x**2 + 2 * x + 1

y.backward()

print("\n------------------------------")
print("Hàm y = 3*x^2 + 2*x + 1")

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

print("\nTính thủ công:")
print("dy/dx = 6x + 2")
print("Tại x = 3.6:")
print("dy/dx =", 6 * 3.6 + 2)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)

Tính thủ công:
y = x^2
dy/dx = 2x
Tại x = 3.6:
dy/dx = 7.2

------------------------------
Hàm y = 3*x^2 + 2*x + 1
x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)

Tính thủ công:
dy/dx = 6x + 2
Tại x = 3.6:
dy/dx = 23.6


In [11]:
# Bài 9: Gradient Descent tìm hệ số đa thức

# Đa thức cần tìm:
# y = x^2 + 2x + 3

polynomial = np.poly1d([1, 2, 3])

N = 20

# Sinh dữ liệu
X = np.random.randn(N, 1) * 5
Y = polynomial(X)

# Tạo ma trận [x^2, x, 1]
XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

# Khởi tạo các hệ số ngẫu nhiên
w = torch.randn(3, 1, requires_grad=True)

# Chuyển sang Tensor
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

# Optimizer
optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

# Huấn luyện
for epoch in range(1000):

    # Xóa gradient cũ
    optimizer.zero_grad()

    # Dự đoán
    y_pred = x @ w

    # Tính MSE
    mse = torch.mean(torch.square(y - y_pred))

    # Tính gradient
    mse.backward()

    # Cập nhật hệ số
    optimizer.step()

print("\nLearned coefficients:")
print(w)

print("\nHệ số thực tế:")
print("[1, 2, 3]")

Initial coefficients:
tensor([[-0.2633],
        [ 0.3517],
        [ 0.3496]], requires_grad=True)

Learned coefficients:
tensor([[1.0152],
        [1.9911],
        [2.1744]], requires_grad=True)

Hệ số thực tế:
[1, 2, 3]


In [12]:
# Bài 10: Giải hệ phương trình bằng Autograd

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000

optimizer = torch.optim.NAdam(
    [A, B, C, D],
    lr=0.01
)

for epoch in range(EPOCHS):

    # Bốn phương trình
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    # Tổng sai số bình phương
    sqerr = (
        y1*y1 +
        y2*y2 +
        y3*y3 +
        y4*y4
    )

    # Xóa gradient
    optimizer.zero_grad()

    # Tính gradient
    sqerr.backward()

    # Cập nhật A, B, C, D
    optimizer.step()

print("Nghiệm tìm được:")

print("A =", A.item())
print("B =", B.item())
print("C =", C.item())
print("D =", D.item())

print("\nKiểm tra hệ phương trình:")

print("A + B =", (A + B).item())
print("C - D =", (C - D).item())
print("A + C =", (A + C).item())
print("B - D =", (B - D).item())

print("\nNghiệm chính xác:")
print("A = 5")
print("B = 4")
print("C = 3")
print("D = 2")

Nghiệm tìm được:
A = 4.585787773132324
B = 4.414152145385742
C = 3.414191484451294
D = 2.4141688346862793

Kiểm tra hệ phương trình:
A + B = 8.999939918518066
C - D = 1.0000226497650146
A + C = 7.999979019165039
B - D = 1.999983310699463

Nghiệm chính xác:
A = 5
B = 4
C = 3
D = 2


In [13]:
# Bài tập áp dụng bài 11
# Tạo Tensor X có 24 phần tử
X = torch.arange(1, 25)

print("Tensor X:")
print(X)

print("\nX reshape thành 4 x 6:")
print(X.reshape(4, 6))

print("\nX reshape thành 2 x 12:")
print(X.reshape(2, 12))

print("\nX reshape thành 2 x 3 x 4:")
print(X.reshape(2, 3, 4))

Tensor X:
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

X reshape thành 4 x 6:
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])

X reshape thành 2 x 12:
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

X reshape thành 2 x 3 x 4:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])


In [14]:

# Tạo hai Tensor A và B kích thước 3 x 4
A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("Tensor A:")
print(A)

print("\nTensor B:")
print(B)

print("\nA + B:")
print(A + B)

print("\nA * B:")
print(A * B)

print("\nA / B:")
print(A / B)

print("\nTrung bình theo cột của A:")
print(torch.mean(A, dim=0))

print("\nĐộ lệch chuẩn theo cột của A:")
print(torch.std(A, dim=0))

Tensor A:
tensor([[-1.0873,  0.0111, -0.4219, -1.1997],
        [-0.5355,  0.2439, -0.8993, -0.3939],
        [ 0.4510,  2.5303, -0.1533,  1.5361]])

Tensor B:
tensor([[-1.5568,  1.7432,  1.4712, -0.3146],
        [ 0.4671, -1.0540,  1.8454,  0.5384],
        [-0.2571,  1.0125,  0.4104, -0.7584]])

A + B:
tensor([[-2.6441,  1.7543,  1.0494, -1.5143],
        [-0.0683, -0.8100,  0.9461,  0.1444],
        [ 0.1940,  3.5428,  0.2571,  0.7777]])

A * B:
tensor([[ 1.6928,  0.0193, -0.6206,  0.3774],
        [-0.2501, -0.2571, -1.6596, -0.2121],
        [-0.1159,  2.5619, -0.0629, -1.1650]])

A / B:
tensor([[ 0.6984,  0.0064, -0.2867,  3.8131],
        [-1.1463, -0.2314, -0.4873, -0.7317],
        [-1.7546,  2.4991, -0.3735, -2.0254]])

Trung bình theo cột của A:
tensor([-0.3906,  0.9284, -0.4915, -0.0192])

Độ lệch chuẩn theo cột của A:
tensor([0.7793, 1.3921, 0.3779, 1.4059])


In [15]:

# Tạo x = 2 và bật tính gradient
x = torch.tensor(2.0, requires_grad=True)

# Hàm y = 2x^2 + 5x + 3
y = 2 * x**2 + 5 * x + 3

# Tính đạo hàm bằng Autograd
y.backward()

print("x =", x.item())
print("y =", y.item())
print("dy/dx bằng Autograd =", x.grad.item())

# Tính thủ công:
# dy/dx = 4x + 5
manual_gradient = 4 * 2 + 5

print("dy/dx tính thủ công =", manual_gradient)

x = 2.0
y = 21.0
dy/dx bằng Autograd = 13.0
dy/dx tính thủ công = 13


In [16]:

# Đa thức y = 2x^2 - 3x + 5
polynomial = np.poly1d([2, -3, 5])

# Tạo dữ liệu
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)

# Tạo ma trận [x^2, x, 1]
XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

# Chuyển dữ liệu sang Tensor
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

# Khởi tạo 3 hệ số ngẫu nhiên
w = torch.randn(3, 1, requires_grad=True)

# Tạo Optimizer
optimizer = torch.optim.NAdam([w], lr=0.01)

print("Hệ số ban đầu:")
print(w.detach())

# Huấn luyện
for epoch in range(1000):
    optimizer.zero_grad()

    y_pred = x @ w

    mse = torch.mean(torch.square(y - y_pred))

    mse.backward()

    optimizer.step()

print("\nHệ số sau khi huấn luyện:")
print(w.detach())

print("\nHệ số thực tế:")
print("[2, -3, 5]")

print("\nMSE:")
print(mse.item())

Hệ số ban đầu:
tensor([[-0.0776],
        [-0.8002],
        [-1.1270]])

Hệ số sau khi huấn luyện:
tensor([[ 2.0476],
        [-2.9035],
        [ 2.0626]])

Hệ số thực tế:
[2, -3, 5]

MSE:
6.190943241119385
